<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class CrudController extends Controller
{
    private function resources(): array { return [
        'annees' => ['table'=>'academic_years','title'=>'Années universitaires','fields'=>['name'=>'Année (ex: 2026/2027)','starts_on'=>'Date début','ends_on'=>'Date fin','is_active'=>'Année active'], 'types'=>['starts_on'=>'date','ends_on'=>'date','is_active'=>'checkbox']],
        'departements' => ['table'=>'departments','title'=>'Départements','fields'=>['name'=>'Nom','code'=>'Code']],
        'filieres' => ['table'=>'programs','title'=>'Filières','fields'=>['department_id'=>'Département','name'=>'Nom','code'=>'Code'], 'selects'=>['department_id'=>['departments','name']]],
        'semestres' => ['table'=>'semesters','title'=>'Semestres','fields'=>['program_id'=>'Filière','academic_year_id'=>'Année','name'=>'Libellé','number'=>'Numéro'], 'types'=>['number'=>'number'], 'selects'=>['program_id'=>['programs','name'],'academic_year_id'=>['academic_years','name']]],
        'modules' => ['table'=>'modules','title'=>'Modules','fields'=>['program_id'=>'Filière','name'=>'Nom','code'=>'Code','weekly_hours'=>'Heures / semaine'], 'types'=>['weekly_hours'=>'number'], 'selects'=>['program_id'=>['programs','name']]],
        'groupes' => ['table'=>'student_groups','title'=>'Groupes','fields'=>['semester_id'=>'Semestre','name'=>'Nom','student_count'=>'Nombre étudiants'], 'types'=>['student_count'=>'number'], 'selects'=>['semester_id'=>['semesters','name']]],
        'salles' => ['table'=>'classrooms','title'=>'Salles','fields'=>['name'=>'Nom','capacity'=>'Capacité','type'=>'Type'], 'types'=>['capacity'=>'number','type'=>'select'], 'options'=>['type'=>['cours'=>'Cours','td'=>'TD','tp'=>'TP','mixte'=>'Mixte']]],
        'professeurs' => ['table'=>'users','title'=>'Utilisateurs et professeurs','fields'=>['name'=>'Nom complet','email'=>'Email','password'=>'Mot de passe','role'=>'Rôle'], 'types'=>['password'=>'password','role'=>'select'], 'options'=>['role'=>array_combine(\App\Models\User::ROLES, \App\Models\User::ROLES)]],
        'seances' => ['table'=>'teaching_sessions','title'=>'Séances à planifier','fields'=>['semester_id'=>'Semestre','module_id'=>'Module','professor_id'=>'Professeur','student_group_id'=>'Groupe','type'=>'Type','duration_minutes'=>'Durée (minutes)','occurrences_per_week'=>'Fois / semaine'], 'types'=>['type'=>'select','duration_minutes'=>'number','occurrences_per_week'=>'number'], 'options'=>['type'=>['cours'=>'Cours','td'=>'TD','tp'=>'TP']], 'selects'=>['semester_id'=>['semesters','name'],'module_id'=>['modules','name'],'professor_id'=>['users','name'],'student_group_id'=>['student_groups','name']]],
        'indisponibilites' => ['table'=>'professor_availabilities','title'=>'Indisponibilités des professeurs','fields'=>['professor_id'=>'Professeur','day_of_week'=>'Jour (1=Lun .. 5=Ven)','start_minute'=>'Début (minutes, 480=08:00)','end_minute'=>'Fin (minutes)','available'=>'Disponible'], 'types'=>['day_of_week'=>'number','start_minute'=>'number','end_minute'=>'number','available'=>'checkbox'], 'selects'=>['professor_id'=>['users','name']]],
        'emplois' => ['table'=>'schedules','title'=>'Versions des emplois du temps','fields'=>['semester_id'=>'Semestre','name'=>'Nom','status'=>'État'], 'types'=>['status'=>'select'], 'options'=>['status'=>['draft'=>'Brouillon','generating'=>'En génération','generated'=>'Généré','partial'=>'Partiel']], 'selects'=>['semester_id'=>['semesters','name']]],
        'creneaux' => ['table'=>'timetable_entries','title'=>'Créneaux planifiés','fields'=>['schedule_id'=>'Emploi','teaching_session_id'=>'Séance (ID)','classroom_id'=>'Salle','day_of_week'=>'Jour (1-5)','start_minute'=>'Début (minutes)','end_minute'=>'Fin (minutes)','occurrence'=>'Occurrence'], 'types'=>['day_of_week'=>'number','start_minute'=>'number','end_minute'=>'number','occurrence'=>'number'], 'selects'=>['schedule_id'=>['schedules','name'],'teaching_session_id'=>['teaching_sessions','id'],'classroom_id'=>['classrooms','name']]],
    ]; }
    private function resource(string $key): array { abort_unless(isset($this->resources()[$key]),404); return $this->resources()[$key]; }
    public function index(string $resource) { $meta=$this->resource($resource); $rows=DB::table($meta['table'])->orderByDesc('id')->paginate(15); return view('crud.index',compact('resource','meta','rows')+['choices'=>$this->choices($meta)]); }
    public function create(string $resource) { $meta=$this->resource($resource); return view('crud.form',['resource'=>$resource,'meta'=>$meta,'row'=>null,'choices'=>$this->choices($meta)]); }
    public function store(Request $request,string $resource) { $meta=$this->resource($resource); $data=$this->validated($request,$meta); DB::table($meta['table'])->insert(array_merge($data,['created_at'=>now(),'updated_at'=>now()])); return redirect()->route('crud.index',$resource)->with('success','Enregistrement ajouté.'); }
    public function edit(string $resource,int $id) { $meta=$this->resource($resource); $row=DB::table($meta['table'])->find($id); abort_unless($row,404); return view('crud.form',compact('resource','meta','row')+['choices'=>$this->choices($meta)]); }
    public function update(Request $request,string $resource,int $id) { $meta=$this->resource($resource); $data=$this->validated($request,$meta,$id); DB::table($meta['table'])->where('id',$id)->update(array_merge($data,['updated_at'=>now()])); return redirect()->route('crud.index',$resource)->with('success','Enregistrement modifié.'); }
    public function destroy(string $resource,int $id) { $meta=$this->resource($resource); if($meta['table']==='users' && auth()->id()===$id) return back()->with('error','Impossible de supprimer votre propre compte.'); try { DB::table($meta['table'])->where('id',$id)->delete(); return back()->with('success','Enregistrement supprimé.'); } catch (\Throwable) { return back()->with('error','Suppression impossible : cet élément est utilisé par une autre donnée.'); } }
    private function choices(array $meta): array { $all=[]; foreach($meta['selects']??[] as $field=>[$table,$label]) $all[$field]=DB::table($table)->orderBy($label)->pluck($label,'id'); return $all; }
    private function validated(Request $request,array $meta,?int $id=null): array { $rules=[]; foreach($meta['fields'] as $field=>$label) { $rules[$field]=($field==='password'&&$id?'nullable':'required').'|max:255'; if(in_array($meta['types'][$field]??'', ['number']))$rules[$field]='required|integer|min:0'; if($field==='email')$rules[$field]='required|email|unique:users,email'.($id?','.$id:''); if(isset($meta['selects'][$field]))$rules[$field]='required|integer'; }
        $data=Validator::make($request->all(),$rules)->validate(); foreach($meta['types']??[] as $field=>$type) if($type==='checkbox')$data[$field]=$request->boolean($field); if($meta['table']==='users'){ if(empty($data['password']))unset($data['password']); else $data['password']=Hash::make($data['password']); } return $data; }
}
