@extends('adminlte::page')
@section('title', $professor->exists ? 'Modifier professeur' : 'Ajouter professeur')
@section('content_header')<h1>{{ $professor->exists ? 'Modifier professeur' : 'Ajouter professeur' }}</h1>@endsection
@section('content')
<div class="card card-primary"><form method="POST" action="{{ $professor->exists ? route('professors.update', $professor) : route('professors.store') }}">@csrf @if($professor->exists) @method('PUT') @endif
<div class="card-body row">
<div class="form-group col-md-6"><label>Nom complet</label><input name="name" class="form-control" value="{{ old('name', $professor->name) }}" required>@error('name')<small class="text-danger">{{ $message }}</small>@enderror</div>
<div class="form-group col-md-6"><label>Email</label><input name="email" type="email" class="form-control" value="{{ old('email', $professor->email) }}" required>@error('email')<small class="text-danger">{{ $message }}</small>@enderror</div>
<div class="form-group col-md-6"><label>Mot de passe {{ $professor->exists ? '(laisser vide pour garder)' : '' }}</label><input name="password" type="password" class="form-control" {{ $professor->exists ? '' : 'required' }}>@error('password')<small class="text-danger">{{ $message }}</small>@enderror</div>
<div class="form-group col-md-6"><label>Maximum heures / semaine</label><input name="max_weekly_hours" type="number" min="0" class="form-control" value="{{ old('max_weekly_hours', $professor->max_weekly_hours) }}"><small class="text-muted">Vide = sans limite.</small></div>
<div class="form-group col-md-6"><label>Filtrer par filière</label><select id="program-filter" class="form-control"><option value="">Toutes les filières</option>@foreach($programs as $program)<option value="{{ $program->id }}">{{ $program->code }} — {{ $program->name }}</option>@endforeach</select></div>
<div class="form-group col-md-6"><label>Filtrer par semestre</label><select id="semester-filter" class="form-control"><option value="">Tous les semestres</option>@foreach($semesters as $semester)<option value="{{ $semester->id }}" data-program="{{ $semester->program_id }}">{{ $semester->program->code ?? '' }} — S{{ $semester->number }}</option>@endforeach</select></div>
<div class="form-group col-12"><label>Modules autorisés <small class="text-muted">(plusieurs choix: Ctrl/Cmd + clic)</small></label><select id="modules" name="module_ids[]" multiple size="12" class="form-control">@php($selected = old('module_ids', $professor->modules->pluck('id')->all()))@foreach($modules as $module)<option value="{{ $module->id }}" data-program="{{ $module->program_id }}" data-semester="{{ $module->semester_id }}" @selected(in_array($module->id, $selected))>{{ $module->code }} — {{ $module->name }}{{ $module->semester ? ' (S'.$module->semester->number.')' : '' }}</option>@endforeach</select>@error('module_ids')<small class="text-danger">{{ $message }}</small>@enderror</div>
</div><div class="card-footer"><button class="btn btn-primary">Enregistrer</button> <a href="{{ route('professors.index') }}" class="btn btn-default">Annuler</a></div></form></div>
@push('js')<script>document.addEventListener('DOMContentLoaded',function(){const p=document.getElementById('program-filter'),s=document.getElementById('semester-filter'),m=document.getElementById('modules');function filter(){if(s.value){p.value=s.options[s.selectedIndex].dataset.program||''}Array.from(s.options).forEach(o=>{o.hidden=!!p.value&&o.dataset.program&&o.dataset.program!==p.value});Array.from(m.options).forEach(o=>{const okProgram=!p.value||o.dataset.program===p.value;const okSemester=!s.value||!o.dataset.semester||o.dataset.semester===s.value;o.hidden=!(okProgram&&okSemester)});}p.addEventListener('change',()=>{if(s.value&&s.options[s.selectedIndex].dataset.program!==p.value)s.value='';filter()});s.addEventListener('change',filter);filter()});</script>@endpush
@endsection
